### ISSUE TITLE
header-nav blocks user from clicking on navigation links

### ISSUE THREAD

**Issue by jpikl** [docpress/docpress-base#253]
It is caused by `div` with `header-nav -expanded` class which overlaps some of the top navigation links.

How to reproduce:

1. Open https://docpress.github.io
2. Open developer tools.
3. Switch to responsive mode.
4. Set device with to 500px.
5. Try to click on *docpress* link on top of the page.

I'm currently using this css as a workaround:

```css
.header-nav.-expanded {
  pointer-events: none;
}
.header-nav.-expanded a {
  pointer-events: auto;
}
```
